/// SGGD Design System — token module marker.
///
/// The token enums (`DSColors`, `DSDimensions`, `DSFontWeights`, `DSFontFamilies`)
/// live in `DSTokens.swift`, which is generated by the shared Style Dictionary
/// pipeline. Run `pnpm tokens:build` from the repo root to (re)generate it.
///
/// This committed file guarantees the `SGGDTokens` target always has at least one
/// source so a fresh checkout compiles before tokens are generated.
public enum SGGDTokens {
    /// Token schema version, bumped when the generated surface changes shape.
    public static let schemaVersion = "0.1.0"
}
